### ISSUE TITLE
Checklist of icons requiring fixes/tweaks

### ISSUE THREAD

**Issue by tag2015** [scummvm/scummvm-icons#322]
This is a WIP list of the icons that may need changes or tweaks. Sorted by name, but well known or commercial games should have the priority over niche games:

- [ ] ags-9hourstodawn - A bit confused, small text
- [ ] ags-46memorylane - Black background should be removed, text may be improved
- [ ] ags-almostblue - This is an in-game screenshot with unneeded extra info
- [ ] ags-breakage - Extra stuff in background
- [ ] ags-danewguys - Characters are very low res
- [ ] ags-downfall2009 - This art is from the remake, should be renamed as ags-downfall2016 and created a new one
- [ ] ags-iamjason - The "I AM" text should use the same font of "JASON". Also the colors should match the rest of the picture
- [ ] ags-inbloom - Almost unreadable
- [ ] ags-myfathersecret - The stars look more like noise
- [ ] ags-reactor09 - Very low res
- [ ] ags-spooks - Extra info should be removed
- [ ] ags-themanisee - Inventory items at the top?
- [ ] gob-gob* - All three are screenshots, should be replaced with higher quality images
- [ ] sci - The text is crooked and the outline looks weird, should match the agi icon 
- [ ] sci-hoyle2 - Screenshot, should be replaced with boxart like the other hoyle games
- [ ] scumm-atlantis - Looks almost like scumm-indy3, maybe add some art?
- [ ] scumm-samnmax - Imperfect halo on the right side

**Comment by GandalfTheWhite80** [comment]
Could you split gob-gob* into 3 different entries?

**Comment by GandalfTheWhite80** [comment]
PS May I add my TODO list as will ?

**Comment by tag2015** [comment]
> Could you split gob-gob* into 3 different entries?

done

**Comment by tag2015** [comment]
> PS May I add my TODO list as will ?

Sure!

**Comment by GandalfTheWhite80** [comment]
Ok added a few - for some I have a work-in-progress version. I will try to show/present them in discord ...

**Comment by tag2015** [comment]
Added the icons with rounded corners to the list. These icons don't really fit with the rest and with the added border they look even smaller.
For blackwell/primordia the original pictures should be readily available

**Comment by tag2015** [comment]
Fixed the rounded blackwell icons and the space quest icons with minor changes to the layouts

**Comment by tag2015** [comment]
Added the Enhanced Ultima games to the list. These could share the same art of the standard version, maybe with just an additional text (ENHANCED or ENHANCED VERSION)

**Comment by GandalfTheWhite80** [comment]
The current ultima icons are distorted... maybe we could fix them first? Started it long time ago but never finished it. Maybe its time now

**Comment by tag2015** [comment]
Added a few entries that (of course, IMHO) could be improved
